### ISSUE TITLE
Code Review 20-04

### ISSUE THREAD

**Issue by federicaulzurrun** [Jawad-Nazari/Leaderboard#3]
So far so good @Jawad-Nazari! 👍 
![tufoin](https://media.giphy.com/media/26xBT8PxeCIvf7Ous/giphy.gif) 

@federicaulzurrun :

- Everything it's perfect and congrats on adding input data to LocalStorage!
- I would make your code even better if you added explanatory comments! check the following link to [JavaScript Best pranctice](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/clean-code/refresher_js_best_practices.md)

@LarryIVC :

- Very good work but you could consider applying the good practices of HTML by applying semantic elements like the main, header, section, etc.

**Comment by LarryIVC** [comment]
Very good work @Jawad-Nazari  but you could consider applying the good practices of HTML by applying semantic elements like the main, header, section, etc.

**Comment by Jawad-Nazari** [comment]
Hi @federicaulzurrun @LarryIVC 👍 

Thank you for your time and for reviewing my code. I will consider your advice while coding next time.
